export const ALL_CATEGORY_REQUEST = 'ALL_CATEGORY_REQUEST';
export const ALL_CATEGORY_SUCCESS = 'ALL_CATEGORY_SUCCESS';
export const ALL_CATEGORY_FAILURE = 'ALL_CATEGORY_FAILURE';
export const CATEGORY_ITEMS_REQUEST = 'CATEGORY_ITEMS_REQUEST';
export const CATEGORY_ITEMS_SUCCESS = 'CATEGORY_ITEMS_SUCCESS';
export const CATEGORY_ITEMS_FAILURE = 'CATEGORY_ITEMS_FAILURE';
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
